baseURL = '/'
languageCode = 'en-us'
title = 'KubeTrain'
theme = ["github.com/RoneoOrg/hugo-shortcode-roneo-button-icon-badge", "github.com/theNewDynamic/gohugo-theme-ananke"]

enableRobotTXT = true
sectionPagesMenu = 'main' # Enable submenus

[params]
mainSections = [] # Disable recent posts in homepage
